DD-272
HMPO/hmpo-app pull request #29
Opened 2024-10-22 12:06 UTC by KLV96

Drop Node 14, 16 and 18 and allowing only 20.x || 22.x and updating the following dependencies: async ^3.2.5 -> ^3.2.6
body-parser ^1.20.2 -> ^2.0.1
debug ^4.3.4 -> ^4.3.7
helmet ^6.2.0 -> ^8.0.0
uuid ^9.0.1 -> ^10.0.0

devDependencies:
eslint ^8.57.0 -> ^9.11.1
express ^4.19.2 -> ^4.21.0
hmpo-components ^6.5.1 -> ^7.0.0
hmpo-config ^3.0.1 -> ^4.0.0
hmpo-i18n ^6.0.2 -> ^7.0.0
hmpo-logger ^7.0.2 -> ^8.0.0
husky ^8.0.3 -> ^9.1.6
mocha ^10.7.0 -> ^10.7.3
nyc ^17.0.0 -> ^17.1.0
Replacing reqres ^3.0.1 with hmpo-reqres 2.0.0
sinon ^18.0.0 -> ^19.0.2

peerDependencies:
hmpo-components >=6 -> >=7
hmpo-config >=3 -> >=4
hmpo-i18n >=6 -> >=7
hmpo-logger >=7 -> >=8

2024-10-22 12:51 UTC, SamChatfield requested changes
A few changes needed.

We also need to remove `test/.eslintrc`

2024-10-22 12:51 UTC, SamChatfield commented on package.json
>    "devDependencies": {
Missing globals as a `devDependency`

2024-10-22 12:51 UTC, SamChatfield commented on package.json
> +    "body-parser": "^2.0.1",
This looks like an unstable version, `latest` is still `1.20.3` so we can stick with that for now. We can have another look at this when we look into updating to Express 5.

2024-10-22 12:51 UTC, SamChatfield commented on eslint.config.js
> +                APP_ROOT: 'readonly',
Should be a test global

2024-10-22 12:51 UTC, SamChatfield commented on eslint.config.js
> +                CONFIG_RESET: 'readonly',
Should be test globals

2024-10-22 12:51 UTC, SamChatfield commented on eslint.config.js
> +module.exports = [
Can we add a global ignore for `example/public/**`? If you happen to have ran the example app it throws loads of lint errors on the built `application.js` without that.

2024-10-22 12:51 UTC, SamChatfield commented on eslint.config.js
> +            ],
Should be able to remove this, it doesn't actually do anything with this config.

2024-10-22 12:51 UTC, SamChatfield commented on eslint.config.js
> +                express: 'readonly',
Not an actual global used anywhere in here, can remove this.

2024-10-22 12:51 UTC, SamChatfield commented on middleware/index.js
> +/* istanbul ignore file */
We don't want to ignore coverage here

2024-10-23 09:57 UTC, msjhall138 approved these changes

2024-10-23 11:22 UTC, imran-gov approved these changes

2024-10-28 08:23 UTC, SamChatfield requested changes

2024-10-28 08:23 UTC, SamChatfield commented on eslint.config.js
> +        ...js.configs.recommended,
This isn't the right place for the base config to go

2024-10-28 08:26 UTC, SamChatfield commented on eslint.config.js
> +module.exports = [
The [global ignore](https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores) for this hasn't gone in the right place

2024-10-28 10:24 UTC, SamChatfield commented on eslint.config.js
> +        ...js.configs.recommended,
See internal ESLint config for how to do a base and global ignores

2024-10-28 13:36 UTC, SamChatfield approved these changes
LGTM

2024-10-28 13:54 UTC, merged